AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  pets_backend
  SAM Template for Pet Shelter Microservices - Learning AWS Architecture

Resources:
  # ==================== DynamoDB Tables ====================

  # DynamoDB Table for storing pet data
  # Note: Uses 'id' as partition key (Number type) per class curriculum
  PetsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Pets
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: N
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      Tags:
        - Key: Project
          Value: PetShelter
        - Key: Environment
          Value: Learning

  # DynamoDB Table for storing adoption applications
  ApplicationsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Applications
      AttributeDefinitions:
        - AttributeName: applicationId
          AttributeType: S
      KeySchema:
        - AttributeName: applicationId
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      Tags:
        - Key: Project
          Value: PetShelter
        - Key: Environment
          Value: Learning

  # ==================== API Gateway ====================

  PetsAPI:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Cors:
        AllowMethods: "'GET,POST,PUT,DELETE,HEAD,OPTIONS'"
        AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
        AllowOrigin: "'*'"

  # ==================== Lambda Functions ====================

  # Lambda Function: GET /pets
  # Retrieves all pets from DynamoDB
  GetPetsFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: getPets
      CodeUri: handlers/get_pets/
      Handler: getPets.lambda_handler
      Runtime: python3.11
      Timeout: 30
      Environment:
        Variables:
          PETS_TABLE: !Ref PetsTable
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref PetsTable
      Events:
        GetPets:
          Type: Api
          Properties:
            RestApiId: !Ref PetsAPI
            Path: /pets
            Method: GET

  # Lambda Function: POST /applications
  # Creates a new adoption application
  CreateApplicationFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: createApplication
      CodeUri: handlers/create_application/
      Handler: createApplication.lambda_handler
      Runtime: python3.11
      Timeout: 30
      Environment:
        Variables:
          APPLICATIONS_TABLE_NAME: !Ref ApplicationsTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ApplicationsTable
      Events:
        CreateApplication:
          Type: Api
          Properties:
            RestApiId: !Ref PetsAPI
            Path: /applications
            Method: POST

  # Lambda Function: GET /applications
  # Retrieves all adoption applications
  GetApplicationsFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: getApplications
      CodeUri: handlers/get_applications/
      Handler: getApplications.lambda_handler
      Runtime: python3.11
      Timeout: 30
      Environment:
        Variables:
          APPLICATIONS_TABLE_NAME: !Ref ApplicationsTable
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref ApplicationsTable
      Events:
        GetApplications:
          Type: Api
          Properties:
            RestApiId: !Ref PetsAPI
            Path: /applications
            Method: GET

Outputs:
  # API Gateway Base URL
  PetsAPIBaseURL:
    Description: "Base URL for Pet Shelter API Gateway"
    Value: !Sub "https://${PetsAPI}.execute-api.${AWS::Region}.amazonaws.com/Prod"
    Export:
      Name: PetsAPIBaseURL

  # Individual API Endpoints
  GetPetsEndpoint:
    Description: "GET /pets - Retrieve all pets"
    Value: !Sub "https://${PetsAPI}.execute-api.${AWS::Region}.amazonaws.com/Prod/pets"

  CreateApplicationEndpoint:
    Description: "POST /applications - Submit adoption application"
    Value: !Sub "https://${PetsAPI}.execute-api.${AWS::Region}.amazonaws.com/Prod/applications"

  GetApplicationsEndpoint:
    Description: "GET /applications - Retrieve all applications"
    Value: !Sub "https://${PetsAPI}.execute-api.${AWS::Region}.amazonaws.com/Prod/applications"

  # DynamoDB Tables
  PetsTableName:
    Description: "DynamoDB table name for Pets"
    Value: !Ref PetsTable
    Export:
      Name: PetsTableName

  ApplicationsTableName:
    Description: "DynamoDB table name for Applications"
    Value: !Ref ApplicationsTable
    Export:
      Name: ApplicationsTableName

  # Region Information
  DeployedRegion:
    Description: "AWS Region where resources are deployed"
    Value: !Ref AWS::Region