AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  pets_backend
  SAM Template for Pet Shelter Microservices - Learning AWS Architecture

Resources:

  # Add a lambda function called "GetAdoptionLambda" that will also be attached to the PetsAPI
  # resource and will be triggered at the route /adoptions/{id} with a GET request
  GetAdoptionLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: handlers/get_adoption
      Handler: getAdoption.lambda_handler
      Runtime: python3.11
      Architectures:
        - x86_64
      Environment:
        Variables:
          ADOPTIONS_TABLE: !Ref AdoptionsTable
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref AdoptionsTable
      Events:
        GetAdoptionApi:
          Type: Api
          Properties:
            RestApiId: !Ref PetsAPI
            Path: /adoptions/{id}
            Method: get   

  # Add a lambda function called "CreateAdoptionLambda" that will also be attached to the PetsAPI
  # resource and will be triggered at the route /adoptions with a POST request
  CreateAdoptionLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: handlers/create_adoption
      Handler: createAdoption.lambda_handler
      Runtime: python3.11
      Architectures:
        - x86_64
      Environment:
        Variables:
          ADOPTIONS_TABLE: !Ref AdoptionsTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref AdoptionsTable
      Events:
        CreateAdoptionApi:
          Type: Api
          Properties:
            RestApiId: !Ref PetsAPI
            Path: /adoptions
            Method: post
            
  # ==================== DynamoDB Tables ====================

  # DynamoDB Table for storing pet data
  # Note: Uses 'id' as partition key (Number type) per class curriculum
  PetsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Pets
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: N
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      Tags:
        - Key: Project
          Value: PetShelter
        - Key: Environment
          Value: Learning

  # DynamoDB Table for storing adoption applications
  ApplicationsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Applications
      AttributeDefinitions:
        - AttributeName: applicationId
          AttributeType: S
      KeySchema:
        - AttributeName: applicationId
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      Tags:
        - Key: Project
          Value: PetShelter
        - Key: Environment
          Value: Learning

  # DynamoDB Table for storing adoptions
  AdoptionsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: AdoptionsTable
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1

  # ==================== API Gateway ====================

  PetsAPI:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Cors:
        AllowMethods: "'GET,POST,PUT,DELETE,HEAD,OPTIONS'"
        AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
        AllowOrigin: "'*'"

  # ==================== Lambda Functions ====================

  # Lambda Function: GET /pets
  # Retrieves all pets from DynamoDB
  GetPetsFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: getPets
      CodeUri: handlers/get_pets/
      Handler: getPets.lambda_handler
      Runtime: python3.11
      Timeout: 30
      Environment:
        Variables:
          PETS_TABLE: !Ref PetsTable
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref PetsTable
      Events:
        GetPets:
          Type: Api
          Properties:
            RestApiId: !Ref PetsAPI
            Path: /pets
            Method: GET

  # Lambda Function: POST /applications
  # Creates a new adoption application
  CreateApplicationFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: createApplication
      CodeUri: handlers/create_application/
      Handler: createApplication.lambda_handler
      Runtime: python3.11
      Timeout: 30
      Environment:
        Variables:
          APPLICATIONS_TABLE_NAME: !Ref ApplicationsTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ApplicationsTable
      Events:
        CreateApplication:
          Type: Api
          Properties:
            RestApiId: !Ref PetsAPI
            Path: /applications
            Method: POST

  # Add a Lambda function called "GetAdoptionsLambda" that uses the Python 3.12 runtime, and is invoked at the path /adoptions with a get method include the proper IAM role.
  GetAdoptionsFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: getAdoptions
      CodeUri: handlers/get_adoptions/
      Handler: getAdoptions.lambda_handler
      Runtime: python3.11
      Timeout: 30
      Environment:
        Variables:
          APPLICATIONS_TABLE_NAME: !Ref AdoptionsTable
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref AdoptionsTable
      Events:
        GetAdoptions:
          Type: Api
          Properties:
            RestApiId: !Ref PetsAPI
            Path: /adoptions
            Method: GET



  # Lambda Function: GET /applications
  # Retrieves all adoption applications
  GetApplicationsFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: getApplications
      CodeUri: handlers/get_applications/
      Handler: getApplications.lambda_handler
      Runtime: python3.11
      Timeout: 30
      Environment:
        Variables:
          APPLICATIONS_TABLE_NAME: !Ref ApplicationsTable
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref ApplicationsTable
      Events:
        GetApplications:
          Type: Api
          Properties:
            RestApiId: !Ref PetsAPI
            Path: /applications
            Method: GET

Outputs:
  # API Gateway Base URL
  PetsAPIBaseURL:
    Description: "Base URL for Pet Shelter API Gateway"
    Value: !Sub "https://${PetsAPI}.execute-api.${AWS::Region}.amazonaws.com/Prod"
    Export:
      Name: PetsAPIBaseURL

  # Individual API Endpoints
  GetPetsEndpoint:
    Description: "GET /pets - Retrieve all pets"
    Value: !Sub "https://${PetsAPI}.execute-api.${AWS::Region}.amazonaws.com/Prod/pets"

  CreateApplicationEndpoint:
    Description: "POST /applications - Submit adoption application"
    Value: !Sub "https://${PetsAPI}.execute-api.${AWS::Region}.amazonaws.com/Prod/applications"

  GetApplicationsEndpoint:
    Description: "GET /applications - Retrieve all applications"
    Value: !Sub "https://${PetsAPI}.execute-api.${AWS::Region}.amazonaws.com/Prod/applications"

  GetAdoptionsEndpoint:
    Description: "GET /adoptions - Retrieve all adoptions"
    Value: !Sub "https://${PetsAPI}.execute-api.${AWS::Region}.amazonaws.com/Prod/adoptions"

  # Add output for the /adoptions API endpoint
  GetAdoptionsAPIEndpoint:
    Description: "API Gateway endpoint URL for Prod stage for GetAdoptions function"
    Value: !Sub "https://${PetsAPI}.execute-api.${AWS::Region}.amazonaws.com/Prod/adoptions/"

  # Output the API endpoint URL for GetAdoptionLambda
  GetAdoptionAPIEndpoint:
    Description: "API Gateway endpoint URL for Prod stage for GetAdoption function"
    Value: !Sub "https://${PetsAPI}.execute-api.${AWS::Region}.amazonaws.com/Prod/adoptions/{id}"

  CreateAdoptionAPIEndpoint:
    Description: "API Gateway endpoint URL for Prod stage for CreateAdoption function"
    Value: !Sub "https://${PetsAPI}.execute-api.${AWS::Region}.amazonaws.com/Prod/adoptions/"

  # DynamoDB Tables
  PetsTableName:
    Description: "DynamoDB table name for Pets"
    Value: !Ref PetsTable
    Export:
      Name: PetsTableName

  ApplicationsTableName:
    Description: "DynamoDB table name for Applications"
    Value: !Ref ApplicationsTable
    Export:
      Name: ApplicationsTableName

  AdoptionsTableName: 
    Description: "DynamoDB table name for Adoptions"
    Value: !Ref AdoptionsTable
    Export:
      Name: AdoptionsTableName

  # Region Information
  DeployedRegion:
    Description: "AWS Region where resources are deployed"
    Value: !Ref AWS::Region